/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.valerian.prolan.chart;

import id.valerian.prolan.connection.db_connection;
import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.jdbc.JDBCPieDataset;

/**
 *
 * @author Valerian
 */
public class gradeChart extends javax.swing.JInternalFrame {

    ResultSet rs;
    JFreeChart chart;
    JFileChooser chooser;
    /**
     * Creates new form gradeChart
     */
    public gradeChart() {
        initComponents();
        try {
            String sql = "SELECT DISTINCT jurusan FROM t_kelas";
            java.sql.Connection conn = (Connection) db_connection.configDB();
            Statement st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                cbJurusan.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        try {
            String sql = "SELECT DISTINCT tahun_ajaran FROM t_nilai";
            java.sql.Connection conn = (Connection) db_connection.configDB();
            Statement st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                cbTA.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        show_chart();
    }

    public void show_chart() {
        try {
            String sql;
            sql = "SELECT t_matpel.nama_mapel AS MataPelajaran,COUNT(*) FROM t_nilai,t_matpel,t_kelas,t_siswa "
                    + "WHERE t_nilai.kd_mapel = t_matpel.kd_mapel AND t_nilai.nipd = t_siswa.nipd "
                    + "AND t_siswa.id_kelas = t_kelas.id_kelas AND t_nilai.keterangan='LULUS' "
                    + "AND t_kelas.jurusan LIKE '"+cbJurusan.getSelectedItem().toString()+"' "
                    + "AND t_kelas.tingkat_kelas LIKE '"+cbKelas.getSelectedItem().toString()+"' "
                    + "AND t_nilai.tahun_ajaran LIKE '"+cbTA.getSelectedItem().toString()+"' "
                    + "GROUP BY t_matpel.kd_mapel";
            java.sql.Connection conn = (Connection) db_connection.configDB();
            JDBCPieDataset dataset = new JDBCPieDataset(conn, sql);
            chart = ChartFactory.createPieChart("Grafik Kelulusan \nTahun Ajaran : "+cbTA.getSelectedItem().toString()+"\nKelas : "+cbKelas.getSelectedItem().toString()+"\nJurusan: "+cbJurusan.getSelectedItem().toString(), dataset, true, true, false);
            ChartPanel chartpanel = new ChartPanel(chart);
            PiePlot plot = (PiePlot) chart.getPlot();
            PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator("{0} = {2}");
            plot.setLabelGenerator(labelGenerator);
            jPanel1.removeAll();
            jPanel1.add(chartpanel, BorderLayout.CENTER);
            jPanel1.validate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbJurusan = new javax.swing.JComboBox<>();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTA = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnSimpan = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Grafik Nilai Siswa");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));

        jLabel1.setText("Kelas :");

        jLabel2.setText("Jurusan");

        jLabel3.setText("Tahun Ajaran");

        jToggleButton1.setText("Lihat Grafik");
        jToggleButton1.setActionCommand("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/save.png"))); // NOI18N
        btnSimpan.setText("Simpan Grafik");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTA, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(btnSimpan)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cbTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        show_chart();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Save");
        chooser.setAcceptAllFileFilterUsed(false);
        FileFilter filter = new FileNameExtensionFilter("PNG", "png");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.showSaveDialog(this);
        File file = chooser.getSelectedFile();
        if (file != null) {
            File pngFile = new File(file.toString() + ".png");
            String file_name = chooser.getSelectedFile().toString();
            if (file.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        String.format("%s already exists.%n Overwrite?", file.getName()),
                        "File already exists", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_graph(file_name);
                }
            }else if(pngFile.exists()){
                int result = JOptionPane.showConfirmDialog(this,
                        String.format("%s.png already exists.%n Overwrite?", file.getName()),
                        "File already exists", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_graph(file_name);
                }
            }else {
                save_graph(file_name);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void save_graph(String file_name) {
        try {
            if (!file_name.toLowerCase().endsWith(".png")) {
                ChartUtilities.saveChartAsPNG(new File(file_name + ".png"), chart, 1024, 768);
            } else if (file_name.toLowerCase().endsWith(".png")) {
                ChartUtilities.saveChartAsPNG(new File(file_name), chart, 1024, 768);
            }
        } catch (Exception ex) {
            Logger.getLogger(studentChart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
