/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.valerian.prolan.chart;

import id.valerian.prolan.connection.db_connection;
import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.jdbc.JDBCPieDataset;

/**
 *
 * @author Valerian
 */
public class studentChart extends javax.swing.JInternalFrame {

    JFreeChart chart;
    JFileChooser chooser;
    String radioSelectedName;
    /**
     * Creates new form chartSiswa
     */
    public studentChart() {
        initComponents();
        btnGroup.add(jRadioButton1);
        btnGroup.add(jRadioButton2);
        btnGroup.add(jRadioButton3);
        show_chart();
    }

    private void show_chart() {
        try {
            String sql = null;
            if (jRadioButton1.isSelected()) {
                sql = "SELECT DISTINCT `Jenis_Kelamin` AS JenisKelamin,COUNT(NIPD) FROM t_siswa GROUP BY Jenis_Kelamin";
                radioSelectedName = "Jenis Kelamin";
            } else if (jRadioButton2.isSelected()) {
                sql = "SELECT DISTINCT t_kelas.jurusan AS Jurusan,COUNT(NIPD) FROM t_kelas,t_siswa WHERE t_siswa.id_kelas = t_kelas.id_kelas GROUP BY t_kelas.jurusan";
                radioSelectedName = "Jurusan";
            } else if (jRadioButton3.isSelected()) {
                sql = "SELECT DISTINCT t_kelas.tingkat_kelas AS TingkatKelas,COUNT(NIPD) FROM t_kelas,t_siswa WHERE t_siswa.id_kelas = t_kelas.id_kelas GROUP BY t_kelas.tingkat_kelas";
                radioSelectedName = "Tingkat Kelas";
            }
            java.sql.Connection conn = (Connection) db_connection.configDB();
            JDBCPieDataset dataset = new JDBCPieDataset(conn, sql);
            DateFormat dateFormat = new SimpleDateFormat("dd/MMM/yyyy");
            Date date = new Date();
            chart = ChartFactory.createPieChart("Grafik Siswa Berdasarkan "+radioSelectedName+"\n" + dateFormat.format(date), dataset, true, true, false);
            ChartPanel chartpanel = new ChartPanel(chart);
            PiePlot plot = (PiePlot) chart.getPlot();
            PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator("{0} = {2}");
            plot.setLabelGenerator(labelGenerator);
            jPanel1.removeAll();
            jPanel1.add(chartpanel, BorderLayout.CENTER);
            jPanel1.validate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Grafik Siswa");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Jenis Kelamin");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Jurusan");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jRadioButton3.setText("Tingkat Kelas");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lihat Chart Berdasarkan :");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/save.png"))); // NOI18N
        btnSimpan.setText("Simpan Grafik");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btnSimpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton2)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        show_chart();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        show_chart();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        show_chart();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Save");
        chooser.setAcceptAllFileFilterUsed(false);
        FileFilter filter = new FileNameExtensionFilter("PNG", "png");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.showSaveDialog(this);
        File file = chooser.getSelectedFile();
        if (file != null) {
            File pngFile = new File(file.toString() + ".png");
            String file_name = chooser.getSelectedFile().toString();
            if (file.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        String.format("%s already exists.%n Overwrite?", file.getName()),
                        "File already exists", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_graph(file_name);
                }
            } else if (pngFile.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        String.format("%s.png already exists.%n Overwrite?", file.getName()),
                        "File already exists", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_graph(file_name);
                }
            } else {
                save_graph(file_name);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void save_graph(String file_name) {
        try {
            if (!file_name.toLowerCase().endsWith(".png")) {
                ChartUtilities.saveChartAsPNG(new File(file_name + ".png"), chart, 1024, 768);
            } else if (file_name.toLowerCase().endsWith(".png")) {
                ChartUtilities.saveChartAsPNG(new File(file_name), chart, 1024, 768);
            }
        } catch (Exception ex) {
            Logger.getLogger(studentChart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
