/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.valerian.prolan.students;

import id.valerian.prolan.connection.db_connection;
import static id.valerian.prolan.user.User.containsNumbers;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Valerian
 */
public class Students extends javax.swing.JInternalFrame {

    ResultSet rs;
    boolean invalid;

    /**
     * Creates new form StudentsIF
     */
    public Students() {
        initComponents();
        show_student();
        btnGroupJK.add(RB1);
        btnGroupJK.add(RB2);
        //Generate ID Kelas from database
        try {
            String sql = "SELECT id_kelas from t_kelas";
            java.sql.Connection conn = (Connection) db_connection.configDB();
            Statement st = conn.createStatement();
            rs = st.executeQuery(sql);
            cbIdKelas.addItem("-Pilihan-");
            while (rs.next()) {
                cbIdKelas.addItem(rs.getString("id_kelas"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtAlamat.setLineWrap(true);
        txtAlamat.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupJK = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        lblData = new javax.swing.JLabel();
        lblCountData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbIdKelas = new javax.swing.JComboBox<>();
        txtTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJurusan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNIPD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        cbAgama = new javax.swing.JComboBox<>();
        txtTempatLahir = new javax.swing.JTextField();
        txtTanggalLahir = new com.toedter.calendar.JDateChooser();
        txtPO = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(null);

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIPD", "Nama", "ID Kelas", "Tingkat Kelas", "Jurusan", "Alamat", "JK", "Agama", "Tempat Lahir", "Tanggal Lahir", "Pekerjaan Ortu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableStudent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStudent);

        lblData.setText("Jumlah Data :");

        lblCountData.setText("10000");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kelas Siswa"));

        jLabel11.setText("ID Kelas");

        cbIdKelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIdKelasItemStateChanged(evt);
            }
        });

        txtTK.setEnabled(false);

        jLabel3.setText("Tingkat Kelas");

        jLabel4.setText("Jurusan");

        txtJurusan.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIdKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Indentitas Siswa"));

        jLabel1.setText("NIPD");

        txtNIPD.setNextFocusableComponent(txtNama);
        txtNIPD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNIPDKeyReleased(evt);
            }
        });

        jLabel2.setText("Nama");

        txtNama.setNextFocusableComponent(txtAlamat);
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        jLabel5.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtAlamat);

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Agama");

        jLabel8.setText("Tempat Lahir");

        jLabel9.setText("Tanggal Lahir");

        jLabel10.setText("Pekerjaan Orangtua");

        RB1.setText("Laki-Laki");

        RB2.setText("Perempuan");

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Pilihan----", "Budha", "Hindu", "Islam", "Katholik", "Konghucu", "Kristen" }));
        cbAgama.setNextFocusableComponent(txtTempatLahir);

        txtTempatLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempatLahirKeyReleased(evt);
            }
        });

        txtTanggalLahir.setToolTipText("");
        txtTanggalLahir.setDateFormatString("dd-MM-yyyy");

        txtPO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPOKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNIPD, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTempatLahir)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB2))
                            .addComponent(txtPO, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RB1)
                            .addComponent(RB2)
                            .addComponent(txtNIPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTempatLahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCetakLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/document.png"))); // NOI18N
        btnCetakLaporan.setText("Cetak Laporan");
        btnCetakLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakLaporanActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/valerian/prolan/images/search.png"))); // NOI18N

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIPD", "Nama", "Jurusan" }));
        cbSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSearchItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountData))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(10, 10, 10)
                                .addComponent(btnEdit)
                                .addGap(10, 10, 10)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset))
                            .addComponent(btnCetakLaporan))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete)
                            .addComponent(btnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetakLaporan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(lblCountData))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStudentMouseClicked
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        int i = tableStudent.getSelectedRow();
        TableModel model = tableStudent.getModel();
        txtNIPD.setEnabled(false);
        txtNIPD.setText(model.getValueAt(i, 0).toString());
        txtNama.setText(model.getValueAt(i, 1).toString());
        cbIdKelas.getModel().setSelectedItem(model.getValueAt(i, 2));
        txtAlamat.setText(model.getValueAt(i, 5).toString());
        switch (model.getValueAt(i, 6).toString()) {
            case "L":
                RB1.setSelected(true);
                break;
            case "P":
                RB2.setSelected(true);
                break;
        }
        cbAgama.getModel().setSelectedItem(model.getValueAt(i, 7).toString());
        txtTempatLahir.setText(model.getValueAt(i, 8).toString());
        txtTanggalLahir.setDate(java.sql.Date.valueOf(model.getValueAt(i, 9).toString()));
        txtPO.setText(model.getValueAt(i, 10).toString());
    }//GEN-LAST:event_tableStudentMouseClicked

    private void cbIdKelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIdKelasItemStateChanged
        try {
            if (!cbIdKelas.getModel().getSelectedItem().equals("-Pilihan-")) {
                String sql = "SELECT jurusan,tingkat_kelas from t_kelas where id_kelas = '" + cbIdKelas.getModel().getSelectedItem().toString() + "'";
                java.sql.Connection conn = (Connection) db_connection.configDB();
                Statement st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                    txtJurusan.setText(rs.getString("jurusan"));
                    txtTK.setText(rs.getString("tingkat_kelas"));
                }
            } else {
                txtTK.setText("");
                txtJurusan.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cbIdKelasItemStateChanged

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
        try {
            HashMap parameter = new HashMap();
            parameter.put("jurusan", "");
            parameter.put("kelas", "");
            Connection conn = db_connection.configDB();
            File file = new File("src/id/valerian/prolan/report/reportStudents.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        invalid = checkField();
        if (!invalid) {
            try {
                String sql = "INSERT INTO t_siswa VALUES ('" + txtNIPD.getText() + "','" + txtNama.getText() + "','" + cbIdKelas.getModel().getSelectedItem().toString() + "','" + txtAlamat.getText() + "','" + checkGender() + "','" + cbAgama.getModel().getSelectedItem().toString() + "','" + txtTempatLahir.getText() + "','" + checkBirthDate() + "','" + txtPO.getText() + "')";
                java.sql.Connection conn = (Connection) db_connection.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penyimpanan data siswa berhasil");
                resetField();
                resetTable();
                show_student();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetField();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int reply = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin untuk menghapus data berikut?", title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM t_siswa WHERE NIPD = '" + txtNIPD.getText() + "'";
                java.sql.Connection conn = (Connection) db_connection.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.executeUpdate();
                resetField();
                resetTable();
                show_student();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        invalid = checkField();
        if (!invalid) {
            try {
                String sql = "UPDATE t_siswa SET Nama_Siswa = '" + txtNama.getText() + "',id_kelas = '" + cbIdKelas.getModel().getSelectedItem().toString() + "',Alamat = '" + txtAlamat.getText() + "',Jenis_Kelamin = '" + checkGender() + "',Tempat_Lahir = '" + txtTempatLahir.getText() + "',Tanggal_Lahir = '" + checkBirthDate() + "',Pekerjaan_Ortu = '" + txtPO.getText() + "' WHERE NIPD = '" + txtNIPD.getText() + "'";
                java.sql.Connection conn = (Connection) db_connection.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.executeUpdate();
                resetField();
                resetTable();
                show_student();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        show_student();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtNIPDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIPDKeyReleased
        Integer nipdLength = txtNIPD.getText().length();
        String subStr = txtNIPD.getText();
        if (nipdLength.compareTo(8) > 0) {
            txtNIPD.setText(subStr.substring(0, nipdLength - 1));
            JOptionPane.showMessageDialog(this, "Maksimal karakter NIPD hanya bisa 8!", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        if (!containsNumbers(subStr)) {
            txtNIPD.setText(subStr.substring(0, nipdLength - 1));
        }
    }//GEN-LAST:event_txtNIPDKeyReleased

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        Integer namaLength = txtNama.getText().length();
        String subStr = txtNama.getText();
        if (namaLength.compareTo(32) > 0) {
            txtNama.setText(subStr.substring(0, namaLength - 1));
            JOptionPane.showMessageDialog(this, "Maksimal karakter Nama hanya bisa 32!", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        if (containsNumbers(subStr)) {
            txtNama.setText(subStr.substring(0, namaLength - 1));
        }
    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        Integer alamatLength = txtAlamat.getText().length();
        String subStr = txtAlamat.getText();
        if (alamatLength.compareTo(50) > 0) {
            txtAlamat.setText(subStr.substring(0, alamatLength - 1));
            JOptionPane.showMessageDialog(this, "Maksimal karakter Alamat hanya bisa 50!", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtAlamatKeyReleased

    private void txtTempatLahirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatLahirKeyReleased
        Integer tempatlahirLength = txtTempatLahir.getText().length();
        String subStr = txtTempatLahir.getText();
        if (tempatlahirLength.compareTo(30) > 0) {
            txtTempatLahir.setText(subStr.substring(0, tempatlahirLength - 1));
            JOptionPane.showMessageDialog(this, "Maksimal karakter tempat Lahir hanya bisa 30!", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        if (containsNumbers(subStr)) {
            txtTempatLahir.setText(subStr.substring(0, tempatlahirLength - 1));
        }
    }//GEN-LAST:event_txtTempatLahirKeyReleased

    private void txtPOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPOKeyReleased
        Integer poLength = txtPO.getText().length();
        String subStr = txtPO.getText();
        if (poLength.compareTo(30) > 0) {
            txtPO.setText(subStr.substring(0, poLength - 1));
            JOptionPane.showMessageDialog(this, "Maksimal karakter tempat Lahir hanya bisa 30!", "Pesan", JOptionPane.WARNING_MESSAGE);
        }
        if (containsNumbers(subStr)) {
            txtPO.setText(subStr.substring(0, poLength - 1));
        }
    }//GEN-LAST:event_txtPOKeyReleased

    private void cbSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSearchItemStateChanged
        show_student();
    }//GEN-LAST:event_cbSearchItemStateChanged

    private boolean checkField() {
        Integer nipdLength = txtNIPD.getText().length();
        if (nipdLength.compareTo(8) < 0) {
            JOptionPane.showMessageDialog(this, "NIPD harus berupa 8 angka", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtNIPD.requestFocus(true);
            return true;
        } else if (txtNIPD.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "NIPD tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtNIPD.requestFocus();
            return true;
        } else if (txtNama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtNama.requestFocus();
            return true;
        } else if (txtAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtAlamat.requestFocus();
            return true;
        } else if (btnGroupJK.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin harus dipilih", "Pesan", JOptionPane.WARNING_MESSAGE);
            return true;
        } else if (cbAgama.getModel().getSelectedItem().equals("----Pilihan----")) {
            JOptionPane.showMessageDialog(null, "Agama tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            cbAgama.requestFocus();
            return true;
        } else if (txtTempatLahir.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tempat Lahir tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtTempatLahir.requestFocus();
            return true;
        } else if (txtTanggalLahir.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Lahir tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            txtTanggalLahir.requestFocus();
            return true;
        } else if (cbIdKelas.getModel().getSelectedItem().equals("-Pilihan-")) {
            JOptionPane.showMessageDialog(null, "ID Kelas tidak boleh kosong", "Pesan", JOptionPane.WARNING_MESSAGE);
            cbIdKelas.requestFocus();
            return true;
        } else {
            return false;
        }
    }

    private String checkBirthDate() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String birthDate = df.format(txtTanggalLahir.getDate());
        return birthDate;
    }

    private String checkGender() {
        String gender = null;
        if (RB1.isSelected()) {
            gender = "L";
        } else if (RB2.isSelected()) {
            gender = "P";
        }
        return gender;
    }

    private void resetField() {
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        txtNIPD.setEnabled(true);
        txtNIPD.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTK.setText("");
        txtJurusan.setText("");
        RB1.setSelected(false);
        RB2.setSelected(false);
        cbAgama.setSelectedIndex(0);
        txtTempatLahir.setText("");
        txtTanggalLahir.setDate(null);
        txtPO.setText("");
        cbIdKelas.setSelectedIndex(0);
        txtNIPD.requestFocus(true);
        txtSearch.setText("");
        txtNIPD.requestFocus(true);
    }

    private void resetTable() {
        DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
        model.setRowCount(0);
    }

    private void show_student() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIPD");
        model.addColumn("Nama");
        model.addColumn("ID Kelas");
        model.addColumn("Tingkat Kelas");
        model.addColumn("Jurusan");
        model.addColumn("Alamat");
        model.addColumn("JK");
        model.addColumn("Agama");
        model.addColumn("Tem.Lahir");
        model.addColumn("Tgl.Lahir");
        model.addColumn("Pekerjaan Ortu");
        try {
            int data_count = 0;
            String sql = null;
            if (cbSearch.getModel().getSelectedItem().equals("NIPD")) {
                sql = "SELECT t_siswa.NIPD, t_siswa.Nama_Siswa,t_siswa.id_kelas, t_kelas.tingkat_kelas, t_kelas.jurusan,t_siswa.Alamat, t_siswa.Jenis_Kelamin, t_siswa.Agama, t_siswa.Tempat_Lahir, t_siswa.Tanggal_Lahir, t_siswa.Pekerjaan_Ortu "
                        + "FROM t_kelas INNER JOIN t_siswa ON t_kelas.id_kelas = t_siswa.id_kelas AND t_siswa.NIPD LIKE '" + txtSearch.getText() + "%' ORDER BY t_siswa.NIPD";
            }else if (cbSearch.getModel().getSelectedItem().equals("Jurusan")) {
                sql = "SELECT t_siswa.NIPD, t_siswa.Nama_Siswa,t_siswa.id_kelas, t_kelas.tingkat_kelas, t_kelas.jurusan,t_siswa.Alamat, t_siswa.Jenis_Kelamin, t_siswa.Agama, t_siswa.Tempat_Lahir, t_siswa.Tanggal_Lahir, t_siswa.Pekerjaan_Ortu "
                        + "FROM T_Kelas INNER JOIN t_siswa ON T_Kelas.id_kelas = t_siswa.id_kelas AND T_Kelas.jurusan LIKE '" + txtSearch.getText() + "%' ORDER BY t_siswa.NIPD";
            }else if (cbSearch.getModel().getSelectedItem().equals("Nama")) {
                sql = "SELECT t_siswa.NIPD, t_siswa.Nama_Siswa,t_siswa.id_kelas, T_Kelas.tingkat_kelas, T_Kelas.jurusan,t_siswa.Alamat, t_siswa.Jenis_Kelamin, t_siswa.Agama, t_siswa.Tempat_Lahir, t_siswa.Tanggal_Lahir, t_siswa.Pekerjaan_Ortu "
                        + "FROM T_Kelas INNER JOIN t_siswa ON T_Kelas.id_kelas = t_siswa.id_kelas AND t_siswa.Nama_Siswa LIKE '" + txtSearch.getText() + "%' ORDER BY t_siswa.NIPD";
            }
            java.sql.Connection conn = (Connection) db_connection.configDB();
            Statement st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("NIPD"), rs.getString("Nama_Siswa"), rs.getString("id_kelas"), rs.getString("tingkat_kelas"), rs.getString("jurusan"), rs.getString("Alamat"), rs.getString("Jenis_Kelamin"), rs.getString("Agama"), rs.getString("Tempat_Lahir"), rs.getString("Tanggal_Lahir"), rs.getString("Pekerjaan_Ortu")});
                data_count++;
            }
            tableStudent.setModel(model);
            lblCountData.setText("" + data_count);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGroupJK;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbIdKelas;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCountData;
    private javax.swing.JLabel lblData;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtNIPD;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPO;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTK;
    private com.toedter.calendar.JDateChooser txtTanggalLahir;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
